# Generated by Django 4.0.8 on 2025-01-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teacher_details_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_type', models.CharField(choices=[('Holiday', 'Holiday'), ('Event', 'Event')], max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': '06. Special Days',
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '05. Chapter'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '04. Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '03. Course Category'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '2. Students'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='interested_categories',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interested_category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='details',
        ),
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_imgs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='default_username', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='teacher_profile_imgs/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(null=True, upload_to='chapter_videos/'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('session_number', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '7. Time Table',
                'unique_together': {('day', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='main.student')),
            ],
            options={
                'verbose_name_plural': '08. Enrolled Courses',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveBigIntegerField(default=0)),
                ('reviews', models.TextField(null=True)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.timetable')),
            ],
            options={
                'verbose_name_plural': 'Attendance System',
                'unique_together': {('student', 'timetable', 'date')},
            },
        ),
    ]
