# Generated by Django 5.1.2 on 2025-01-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_specialday_alter_chapter_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"verbose_name_plural": "5. Chapter"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "4. Course"},
        ),
        migrations.AlterModelOptions(
            name="coursecategory",
            options={"verbose_name_plural": "3. Course Category"},
        ),
        migrations.AlterModelOptions(
            name="specialday",
            options={"verbose_name_plural": "6. Special Days"},
        ),
        migrations.AlterModelOptions(
            name="studentcourseenrollment",
            options={"verbose_name_plural": "8. Enrolled Courses"},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="profile_img",
            new_name="student_profile_img",
        ),
        migrations.RemoveField(
            model_name="student",
            name="face_encoding",
        ),
        migrations.DeleteModel(
            name="AttendanceSystem",
        ),
    ]
